// Code generated by thriftgo (0.3.6). DO NOT EDIT.

package chiwei_bot

import (
	"context"
	"fmt"

	"github.com/apache/thrift/lib/go/thrift"

	"github.com/bezhai/multi-bot-task/code/biz/model/conf"
)

type ChiweiBotService interface {
	GetStringValue(ctx context.Context, request *conf.GetStringValueRequest) (r *conf.GetStringValueResponse, err error)
}

type ChiweiBotServiceClient struct {
	c thrift.TClient
}

func NewChiweiBotServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ChiweiBotServiceClient {
	return &ChiweiBotServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewChiweiBotServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ChiweiBotServiceClient {
	return &ChiweiBotServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewChiweiBotServiceClient(c thrift.TClient) *ChiweiBotServiceClient {
	return &ChiweiBotServiceClient{
		c: c,
	}
}

func (p *ChiweiBotServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *ChiweiBotServiceClient) GetStringValue(ctx context.Context, request *conf.GetStringValueRequest) (r *conf.GetStringValueResponse, err error) {
	var _args ChiweiBotServiceGetStringValueArgs
	_args.Request = request
	var _result ChiweiBotServiceGetStringValueResult
	if err = p.Client_().Call(ctx, "GetStringValue", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type ChiweiBotServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      ChiweiBotService
}

func (p *ChiweiBotServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *ChiweiBotServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *ChiweiBotServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewChiweiBotServiceProcessor(handler ChiweiBotService) *ChiweiBotServiceProcessor {
	self := &ChiweiBotServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("GetStringValue", &chiweiBotServiceProcessorGetStringValue{handler: handler})
	return self
}
func (p *ChiweiBotServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type chiweiBotServiceProcessorGetStringValue struct {
	handler ChiweiBotService
}

func (p *chiweiBotServiceProcessorGetStringValue) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := ChiweiBotServiceGetStringValueArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetStringValue", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := ChiweiBotServiceGetStringValueResult{}
	var retval *conf.GetStringValueResponse
	if retval, err2 = p.handler.GetStringValue(ctx, args.Request); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetStringValue: "+err2.Error())
		oprot.WriteMessageBegin("GetStringValue", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetStringValue", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type ChiweiBotServiceGetStringValueArgs struct {
	Request *conf.GetStringValueRequest `thrift:"request,1"`
}

func NewChiweiBotServiceGetStringValueArgs() *ChiweiBotServiceGetStringValueArgs {
	return &ChiweiBotServiceGetStringValueArgs{}
}

var ChiweiBotServiceGetStringValueArgs_Request_DEFAULT *conf.GetStringValueRequest

func (p *ChiweiBotServiceGetStringValueArgs) GetRequest() (v *conf.GetStringValueRequest) {
	if !p.IsSetRequest() {
		return ChiweiBotServiceGetStringValueArgs_Request_DEFAULT
	}
	return p.Request
}

var fieldIDToName_ChiweiBotServiceGetStringValueArgs = map[int16]string{
	1: "request",
}

func (p *ChiweiBotServiceGetStringValueArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *ChiweiBotServiceGetStringValueArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ChiweiBotServiceGetStringValueArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ChiweiBotServiceGetStringValueArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Request = conf.NewGetStringValueRequest()
	if err := p.Request.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *ChiweiBotServiceGetStringValueArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetStringValue_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ChiweiBotServiceGetStringValueArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("request", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Request.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *ChiweiBotServiceGetStringValueArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChiweiBotServiceGetStringValueArgs(%+v)", *p)

}

type ChiweiBotServiceGetStringValueResult struct {
	Success *conf.GetStringValueResponse `thrift:"success,0,optional"`
}

func NewChiweiBotServiceGetStringValueResult() *ChiweiBotServiceGetStringValueResult {
	return &ChiweiBotServiceGetStringValueResult{}
}

var ChiweiBotServiceGetStringValueResult_Success_DEFAULT *conf.GetStringValueResponse

func (p *ChiweiBotServiceGetStringValueResult) GetSuccess() (v *conf.GetStringValueResponse) {
	if !p.IsSetSuccess() {
		return ChiweiBotServiceGetStringValueResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_ChiweiBotServiceGetStringValueResult = map[int16]string{
	0: "success",
}

func (p *ChiweiBotServiceGetStringValueResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChiweiBotServiceGetStringValueResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ChiweiBotServiceGetStringValueResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ChiweiBotServiceGetStringValueResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = conf.NewGetStringValueResponse()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *ChiweiBotServiceGetStringValueResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("GetStringValue_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ChiweiBotServiceGetStringValueResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *ChiweiBotServiceGetStringValueResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChiweiBotServiceGetStringValueResult(%+v)", *p)

}
