// Code generated by hertz generator.

package chiwei_bot

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/bezhai/multi-bot-task/biz/model/conf"
	"github.com/bezhai/multi-bot-task/biz/service/conf_value"
	"github.com/bezhai/multi-bot-task/biz/utils/respx"
)

// GetStringValue .
// @router /api/conf/string_value [GET]
func GetStringValue(ctx context.Context, c *app.RequestContext) {
	var err error
	var req conf.GetStringValueRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	value, err := conf_value.GetConfStringValue(ctx, req.Key)
	if err != nil {
		respx.Fail(c, -1, err.Error())
		return
	}

	respx.SuccessWith(c, &conf.GetStringValueResponseData{Value: value})
}
