// Code generated by hertz generator.

package main

import (
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"

	"github.com/bezhai/multi-bot-task/biz/clients/http_client"
	"github.com/bezhai/multi-bot-task/biz/clients/lark_client"
	"github.com/bezhai/multi-bot-task/biz/clients/mongo_client"
	"github.com/bezhai/multi-bot-task/biz/clients/oss_client"
	"github.com/bezhai/multi-bot-task/biz/clients/redis_client"
)

func main() {
	h := server.Default(server.WithMaxRequestBodySize(20<<24), server.WithWriteTimeout(60*time.Second))
	h.Use(cors.New(cors.Config{
		AllowAllOrigins: true,
		AllowMethods:    []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders:    []string{"Content-Type", "Dnt", "Referer", "User-Agent", "Origin"},
	}))

	http_client.InitHttpClient()
	lark_client.InitOfficialBot()
	mongo_client.InitMongoDb()
	redis_client.InitRedis()
	oss_client.InitOssClient()

	register(h)
	h.Spin()
}
