// Code generated by hertz generator.

package main

import (
	"context"
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"

	"github.com/bezhai/multi-bot-task/biz/dal"
	"github.com/bezhai/multi-bot-task/biz/service/authx"
)

func main() {
	h := server.Default(server.WithMaxRequestBodySize(20<<24), server.WithWriteTimeout(60*time.Second))
	h.Use(cors.New(cors.Config{
		AllowOrigins: []string{"http://localhost:3000", "https://www.yuanzhi.xyz"},
		AllowMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowHeaders: []string{"Content-Type", "Dnt", "Referer", "User-Agent", "Origin", "Authorization"},
	}))

	dal.Init()
	authx.InitAuthMiddleware(context.Background())

	register(h)
	h.Spin()
}
