// Code generated by hertz generator.

package chiwei_bot

import (
	"github.com/bezhai/go_utils/httpx"
	"github.com/cloudwego/hertz/pkg/app"

	"github.com/bezhai/multi-bot-task/utils/env_utils"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _confMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstringvalueMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _need_authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _need_skMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		httpx.ServerAuthMiddleware(env_utils.Value("HTTP_SECRET")),
	}
}

func _data_transMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadtosfiletolarkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _image_storeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpixivimagemetainfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepixivimagestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _translationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetranslationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtranslationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetranslationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adddownloadtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmembervalueMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setmembervalueMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setstringvalueMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _proxyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _data_trans0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadpixivimageMw() []app.HandlerFunc {
	// your code...
	return nil
}
