// Code generated by hertz generator.

package chiwei_bot

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _confMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstringvalueMw() []app.HandlerFunc {
	// your code...
	return nil
}
