// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameModuleAccess = "module_access"

// ModuleAccess 存储模块准入权限
type ModuleAccess struct {
	ID   int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:模块准入权限ID，主键" json:"id"` // 模块准入权限ID，主键
	Name string `gorm:"column:name;type:varchar(100);not null;comment:模块名称" json:"name"`                // 模块名称
}

// TableName ModuleAccess's table name
func (*ModuleAccess) TableName() string {
	return TableNameModuleAccess
}
