// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserModuleAccess = "user_module_access"

// UserModuleAccess 关联用户和模块准入权限
type UserModuleAccess struct {
	UserID         int32 `gorm:"column:user_id;type:int;primaryKey;comment:用户ID" json:"user_id"`                                                         // 用户ID
	ModuleAccessID int32 `gorm:"column:module_access_id;type:int;primaryKey;index:module_access_id,priority:1;comment:模块准入权限ID" json:"module_access_id"` // 模块准入权限ID
}

// TableName UserModuleAccess's table name
func (*UserModuleAccess) TableName() string {
	return TableNameUserModuleAccess
}
